# Generated by Django 3.1.3 on 2021-01-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210121_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='date',
            field=models.DateField(auto_created=True),
        ),
    ]
