# Generated by Django 3.1.3 on 2021-01-22 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210122_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='date',
        ),
    ]
